// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type PrStatus string

const (
	PrStatusOPEN   PrStatus = "OPEN"
	PrStatusMERGED PrStatus = "MERGED"
)

func (e *PrStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PrStatus(s)
	case string:
		*e = PrStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PrStatus: %T", src)
	}
	return nil
}

type NullPrStatus struct {
	PrStatus PrStatus `json:"pr_status"`
	Valid    bool     `json:"valid"` // Valid is true if PrStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPrStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PrStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PrStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPrStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PrStatus), nil
}

type PullRequest struct {
	PullRequestID   string             `json:"pull_request_id"`
	PullRequestName string             `json:"pull_request_name"`
	AuthorID        string             `json:"author_id"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	MergedAt        pgtype.Timestamptz `json:"merged_at"`
}

type Reviewer struct {
	PullRequestID string             `json:"pull_request_id"`
	UserID        string             `json:"user_id"`
	AssignedAt    pgtype.Timestamptz `json:"assigned_at"`
}

type Team struct {
	ID       int32  `json:"id"`
	TeamName string `json:"team_name"`
}

type User struct {
	UserID   string      `json:"user_id"`
	Username string      `json:"username"`
	IsActive bool        `json:"is_active"`
	TeamID   pgtype.Int4 `json:"team_id"`
}
