// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pull_requests.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPullRequest = `-- name: CreatePullRequest :one
INSERT INTO pull_requests (
    pull_request_id, 
    pull_request_name, 
    author_id, 
    status,
    created_at
)
VALUES ($1, $2, $3, $4, $5)
RETURNING pull_request_id, pull_request_name, author_id, status, created_at, merged_at
`

type CreatePullRequestParams struct {
	PullRequestID   string             `json:"pull_request_id"`
	PullRequestName string             `json:"pull_request_name"`
	AuthorID        string             `json:"author_id"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreatePullRequest(ctx context.Context, arg CreatePullRequestParams) (PullRequest, error) {
	row := q.db.QueryRow(ctx, createPullRequest,
		arg.PullRequestID,
		arg.PullRequestName,
		arg.AuthorID,
		arg.Status,
		arg.CreatedAt,
	)
	var i PullRequest
	err := row.Scan(
		&i.PullRequestID,
		&i.PullRequestName,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.MergedAt,
	)
	return i, err
}

const getOpenPRs = `-- name: GetOpenPRs :many
SELECT 
    pull_request_id, 
    pull_request_name, 
    author_id, 
    status,
    created_at,
    merged_at
FROM pull_requests
WHERE status = 'OPEN'
ORDER BY created_at DESC
`

func (q *Queries) GetOpenPRs(ctx context.Context) ([]PullRequest, error) {
	rows, err := q.db.Query(ctx, getOpenPRs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PullRequest{}
	for rows.Next() {
		var i PullRequest
		if err := rows.Scan(
			&i.PullRequestID,
			&i.PullRequestName,
			&i.AuthorID,
			&i.Status,
			&i.CreatedAt,
			&i.MergedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPRsByAuthor = `-- name: GetPRsByAuthor :many
SELECT 
    pull_request_id, 
    pull_request_name, 
    author_id, 
    status,
    created_at,
    merged_at
FROM pull_requests
WHERE author_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetPRsByAuthor(ctx context.Context, authorID string) ([]PullRequest, error) {
	rows, err := q.db.Query(ctx, getPRsByAuthor, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PullRequest{}
	for rows.Next() {
		var i PullRequest
		if err := rows.Scan(
			&i.PullRequestID,
			&i.PullRequestName,
			&i.AuthorID,
			&i.Status,
			&i.CreatedAt,
			&i.MergedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPullRequestByID = `-- name: GetPullRequestByID :one
SELECT 
    pull_request_id, 
    pull_request_name, 
    author_id, 
    status,
    created_at,
    merged_at
FROM pull_requests
WHERE pull_request_id = $1
`

func (q *Queries) GetPullRequestByID(ctx context.Context, pullRequestID string) (PullRequest, error) {
	row := q.db.QueryRow(ctx, getPullRequestByID, pullRequestID)
	var i PullRequest
	err := row.Scan(
		&i.PullRequestID,
		&i.PullRequestName,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.MergedAt,
	)
	return i, err
}

const pRExists = `-- name: PRExists :one
SELECT EXISTS(
    SELECT 1 FROM pull_requests WHERE pull_request_id = $1
)
`

func (q *Queries) PRExists(ctx context.Context, pullRequestID string) (bool, error) {
	row := q.db.QueryRow(ctx, pRExists, pullRequestID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updatePRStatus = `-- name: UpdatePRStatus :one
UPDATE pull_requests
SET 
    status = $2,
    merged_at = $3
WHERE pull_request_id = $1
RETURNING pull_request_id, pull_request_name, author_id, status, created_at, merged_at
`

type UpdatePRStatusParams struct {
	PullRequestID string             `json:"pull_request_id"`
	Status        string             `json:"status"`
	MergedAt      pgtype.Timestamptz `json:"merged_at"`
}

func (q *Queries) UpdatePRStatus(ctx context.Context, arg UpdatePRStatusParams) (PullRequest, error) {
	row := q.db.QueryRow(ctx, updatePRStatus, arg.PullRequestID, arg.Status, arg.MergedAt)
	var i PullRequest
	err := row.Scan(
		&i.PullRequestID,
		&i.PullRequestName,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.MergedAt,
	)
	return i, err
}
