// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reviewers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addReviewer = `-- name: AddReviewer :exec
INSERT INTO reviewers (pull_request_id, user_id, assigned_at)
VALUES ($1, $2, $3)
`

type AddReviewerParams struct {
	PullRequestID string             `json:"pull_request_id"`
	UserID        string             `json:"user_id"`
	AssignedAt    pgtype.Timestamptz `json:"assigned_at"`
}

func (q *Queries) AddReviewer(ctx context.Context, arg AddReviewerParams) error {
	_, err := q.db.Exec(ctx, addReviewer, arg.PullRequestID, arg.UserID, arg.AssignedAt)
	return err
}

const getPRsByReviewer = `-- name: GetPRsByReviewer :many
SELECT 
    pr.pull_request_id,
    pr.pull_request_name,
    pr.author_id,
    pr.status
FROM pull_requests pr
JOIN reviewers rev ON pr.pull_request_id = rev.pull_request_id
WHERE rev.user_id = $1
ORDER BY pr.created_at DESC
`

type GetPRsByReviewerRow struct {
	PullRequestID   string `json:"pull_request_id"`
	PullRequestName string `json:"pull_request_name"`
	AuthorID        string `json:"author_id"`
	Status          string `json:"status"`
}

func (q *Queries) GetPRsByReviewer(ctx context.Context, userID string) ([]GetPRsByReviewerRow, error) {
	rows, err := q.db.Query(ctx, getPRsByReviewer, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPRsByReviewerRow{}
	for rows.Next() {
		var i GetPRsByReviewerRow
		if err := rows.Scan(
			&i.PullRequestID,
			&i.PullRequestName,
			&i.AuthorID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewerCount = `-- name: GetReviewerCount :one
SELECT COUNT(*)
FROM reviewers
WHERE pull_request_id = $1
`

func (q *Queries) GetReviewerCount(ctx context.Context, pullRequestID string) (int64, error) {
	row := q.db.QueryRow(ctx, getReviewerCount, pullRequestID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getReviewersByPR = `-- name: GetReviewersByPR :many
SELECT user_id, assigned_at
FROM reviewers
WHERE pull_request_id = $1
ORDER BY assigned_at
`

type GetReviewersByPRRow struct {
	UserID     string             `json:"user_id"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
}

func (q *Queries) GetReviewersByPR(ctx context.Context, pullRequestID string) ([]GetReviewersByPRRow, error) {
	rows, err := q.db.Query(ctx, getReviewersByPR, pullRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReviewersByPRRow{}
	for rows.Next() {
		var i GetReviewersByPRRow
		if err := rows.Scan(&i.UserID, &i.AssignedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isUserReviewer = `-- name: IsUserReviewer :one
SELECT EXISTS(
    SELECT 1 
    FROM reviewers 
    WHERE pull_request_id = $1 AND user_id = $2
)
`

type IsUserReviewerParams struct {
	PullRequestID string `json:"pull_request_id"`
	UserID        string `json:"user_id"`
}

func (q *Queries) IsUserReviewer(ctx context.Context, arg IsUserReviewerParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserReviewer, arg.PullRequestID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeReviewer = `-- name: RemoveReviewer :exec
DELETE FROM reviewers
WHERE pull_request_id = $1 AND user_id = $2
`

type RemoveReviewerParams struct {
	PullRequestID string `json:"pull_request_id"`
	UserID        string `json:"user_id"`
}

func (q *Queries) RemoveReviewer(ctx context.Context, arg RemoveReviewerParams) error {
	_, err := q.db.Exec(ctx, removeReviewer, arg.PullRequestID, arg.UserID)
	return err
}

const replaceReviewer = `-- name: ReplaceReviewer :exec
WITH deleted AS (
    DELETE FROM reviewers r
    WHERE r.pull_request_id = $1 AND r.user_id = $2
)
INSERT INTO reviewers (pull_request_id, user_id, assigned_at)
VALUES ($1, $3, $4)
ON CONFLICT DO NOTHING
`

type ReplaceReviewerParams struct {
	PullRequestID string             `json:"pull_request_id"`
	UserID        string             `json:"user_id"`
	UserID_2      string             `json:"user_id_2"`
	AssignedAt    pgtype.Timestamptz `json:"assigned_at"`
}

func (q *Queries) ReplaceReviewer(ctx context.Context, arg ReplaceReviewerParams) error {
	_, err := q.db.Exec(ctx, replaceReviewer,
		arg.PullRequestID,
		arg.UserID,
		arg.UserID_2,
		arg.AssignedAt,
	)
	return err
}
