// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (team_name)
VALUES ($1)
RETURNING id, team_name
`

func (q *Queries) CreateTeam(ctx context.Context, teamName string) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, teamName)
	var i Team
	err := row.Scan(&i.ID, &i.TeamName)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams
WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, team_name
FROM teams
WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id int32) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(&i.ID, &i.TeamName)
	return i, err
}

const getTeamByName = `-- name: GetTeamByName :one
SELECT id, team_name
FROM teams
WHERE team_name = $1
`

func (q *Queries) GetTeamByName(ctx context.Context, teamName string) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByName, teamName)
	var i Team
	err := row.Scan(&i.ID, &i.TeamName)
	return i, err
}

const getTeamMemberCount = `-- name: GetTeamMemberCount :one
SELECT COUNT(*) 
FROM users 
WHERE team_id = $1
`

func (q *Queries) GetTeamMemberCount(ctx context.Context, teamID pgtype.Int4) (int64, error) {
	row := q.db.QueryRow(ctx, getTeamMemberCount, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTeams = `-- name: GetTeams :many
SELECT id, team_name
FROM teams
`

func (q *Queries) GetTeams(ctx context.Context) ([]Team, error) {
	rows, err := q.db.Query(ctx, getTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(&i.ID, &i.TeamName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const teamExists = `-- name: TeamExists :one
SELECT EXISTS(
    SELECT 1 FROM teams WHERE team_name = $1
)
`

func (q *Queries) TeamExists(ctx context.Context, teamName string) (bool, error) {
	row := q.db.QueryRow(ctx, teamExists, teamName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateTeam = `-- name: UpdateTeam :exec
UPDATE teams
SET team_name = $2
WHERE id = $1
`

type UpdateTeamParams struct {
	ID       int32  `json:"id"`
	TeamName string `json:"team_name"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) error {
	_, err := q.db.Exec(ctx, updateTeam, arg.ID, arg.TeamName)
	return err
}
