// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (user_id, username, is_active)
VALUES ($1, $2, $3)
RETURNING user_id, username, is_active
`

type CreateUserParams struct {
	UserID   string `json:"user_id"`
	Username string `json:"username"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.UserID, arg.Username, arg.IsActive)
	var i User
	err := row.Scan(&i.UserID, &i.Username, &i.IsActive)
	return i, err
}

const getActiveTeamMembers = `-- name: GetActiveTeamMembers :many
SELECT u.user_id, u.username, u.is_active
FROM users u
JOIN team_members tm ON u.user_id = tm.user_id
WHERE tm.team_id = $1 AND u.is_active = true
`

func (q *Queries) GetActiveTeamMembers(ctx context.Context, teamID int32) ([]User, error) {
	rows, err := q.db.Query(ctx, getActiveTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.UserID, &i.Username, &i.IsActive); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, username, is_active
FROM users
WHERE user_id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i User
	err := row.Scan(&i.UserID, &i.Username, &i.IsActive)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users
SET is_active = $2
WHERE user_id = $1
RETURNING user_id, username, is_active
`

type UpdateUserStatusParams struct {
	UserID   string `json:"user_id"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.UserID, arg.IsActive)
	var i User
	err := row.Scan(&i.UserID, &i.Username, &i.IsActive)
	return i, err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS (
    SELECT 1 FROM users WHERE user_id = $1
)
`

func (q *Queries) UserExists(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
