// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (user_id, username, is_active, team_id)
VALUES ($1, $2, $3, $4)
RETURNING user_id, username, is_active, team_id
`

type CreateUserParams struct {
	UserID   string      `json:"user_id"`
	Username string      `json:"username"`
	IsActive bool        `json:"is_active"`
	TeamID   pgtype.Int4 `json:"team_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserID,
		arg.Username,
		arg.IsActive,
		arg.TeamID,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.IsActive,
		&i.TeamID,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE user_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUser, userID)
	return err
}

const getActiveUsers = `-- name: GetActiveUsers :many
SELECT user_id, username, is_active, team_id
FROM users
WHERE is_active = true
`

func (q *Queries) GetActiveUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getActiveUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.IsActive,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveUsersByTeamID = `-- name: GetActiveUsersByTeamID :many
SELECT user_id, username, is_active, team_id
FROM users
WHERE team_id = $1 AND is_active = true
`

func (q *Queries) GetActiveUsersByTeamID(ctx context.Context, teamID pgtype.Int4) ([]User, error) {
	rows, err := q.db.Query(ctx, getActiveUsersByTeamID, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.IsActive,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamByUserID = `-- name: GetTeamByUserID :one
SELECT user_id, username, is_active, team_id FROM teams t
JOIN users u ON u.team_id = t.id
WHERE u.user_id = $1
`

func (q *Queries) GetTeamByUserID(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRow(ctx, getTeamByUserID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.IsActive,
		&i.TeamID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, username, is_active, team_id
FROM users
WHERE user_id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.IsActive,
		&i.TeamID,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT user_id, username, is_active, team_id
FROM users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.IsActive,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByTeamID = `-- name: GetUsersByTeamID :many
SELECT user_id, username, is_active, team_id
FROM users
WHERE team_id = $1
`

func (q *Queries) GetUsersByTeamID(ctx context.Context, teamID pgtype.Int4) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByTeamID, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.IsActive,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET username = $2, is_active = $3, team_id = $4
WHERE user_id = $1
`

type UpdateUserParams struct {
	UserID   string      `json:"user_id"`
	Username string      `json:"username"`
	IsActive bool        `json:"is_active"`
	TeamID   pgtype.Int4 `json:"team_id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.UserID,
		arg.Username,
		arg.IsActive,
		arg.TeamID,
	)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users
SET is_active = $2
WHERE user_id = $1
RETURNING user_id, username, is_active
`

type UpdateUserStatusParams struct {
	UserID   string `json:"user_id"`
	IsActive bool   `json:"is_active"`
}

type UpdateUserStatusRow struct {
	UserID   string `json:"user_id"`
	Username string `json:"username"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (UpdateUserStatusRow, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.UserID, arg.IsActive)
	var i UpdateUserStatusRow
	err := row.Scan(&i.UserID, &i.Username, &i.IsActive)
	return i, err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS (
    SELECT 1 FROM users WHERE user_id = $1
)
`

func (q *Queries) UserExists(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
